name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site contents
        uses: actions/upload-pages-artifact@v1
        with:
          # Use '.' to publish repo root. Change to 'docs' if your site lives in /docs.
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2